### ISSUE TITLE
Request: An option to recharge jetpacks using fuel instead of RF

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BlakeBr0/IronJetpacks#1]
RF is great, but in the pack I'm working on I'd like to diversify the power sources a bit. I would also like to make all of the flight options in the pack have different advantages and tradeoffs so they're sidegrades rather than direct upgrades.

To accomplish this, I'd like to make Iron Jetpacks use fuel. There doesn't appear to be a config option for this, and I wasn't able to find any relevant settings in the json file.

**Comment by BlakeBr0** [comment]
I'm going to close this as out of scope. While it's a cool idea that I would've liked to add it increases the scope of the mod a little too much for my liking.
