### ISSUE TITLE
[1.14.4] Issue with dedicated server and players. at net.minecraftforge.fml.network.simple.SimpleChannel.sendToServer(Simpl

### ISSUE THREAD

**Issue by ProsperCraft** [BlakeBr0/IronJetpacks#10]
So after some time of play on a fresh world users started having timeouts, and one user crashed, nobody has a jetpack yet.

here is the client crash-

This is what caught my eye- at net.minecraftforge.fml.network.simple.SimpleChannel.sendToServer(Simpl

https://gist.github.com/ProsperCraft/2b4a4edefe40d46524b2ea7e60aefa84

Here is the complete log-
[latest.log](https://github.com/BlakeBr0/IronJetpacks/files/3489118/latest.log)

Version-
IronJetpacks-1.14.4-2.0.1
forge 
.45

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by BlakeBr0** [comment]
I'm not sure what would cause this or how to reproduce it.

**Comment by ProsperCraft** [comment]
All I can say is the network issues with players getting kicked for timeouts resolved when we removed it.

**Comment by ProsperCraft** [comment]
Client crash showing client trying to send data to the server when the mod isn't even on the server.

If lots of clients are doing this perhaps that could cause timeouts?

**https://gist.github.com/Wissi/3b93ff9175d6a26d93806d18047fe5ec**

**Comment by BlakeBr0** [comment]
You sure there isn't another mod causing this? Maybe random patches is doing something? The crash log doesn't really tell me anything and I can't get it to happen with just iron jetpacks installed.

**Comment by Tommeh1** [comment]
We're running into the same issue, even after removing RandomPatches

**Comment by ProsperCraft** [comment]
I can't offer more help here as we quit including it in the pack.
