### ISSUE TITLE
Jetpacks breaking instantly upon taking any hostile damage.

### ISSUE THREAD

**Issue by AnonymousPepper** [BlakeBr0/IronJetpacks#101]
Just put your expensive jetpack on, go get hit in the face by a mob, enjoy that lovely lovely item breaking sound. Can be very reliably repeated on all available jetpacks.

Tested on a fresh game running nothing save latest 1.21.1 NeoForge, latest Iron Jetpacks plus latest dependency, and latest JEI, though obviously it affects other modpacks as well.

**Comment by RIExJonny** [comment]
haha someone beat me to it sorry for resmitting it blake and thank you agine for fixing them the first time
