### ISSUE TITLE
Having multiple jetpacks in inventory somehow results in their stats combining.

### ISSUE THREAD

**Issue by fmbellomy** [BlakeBr0/IronJetpacks#105]
**Describe the bug**
Flying speed with a jetpack equipped in the chest slot and an empty inventory is noticeably slower than flying speed while multiple jetpacks are present in the inventory.

**To Reproduce**
Set up a neoforge 1.21.1 instance with only IronJetpacks, Cucumber Library, and the Curios API (or accessories and its curio compat layer, the bug happens with both.)
Then, in either singleplayer or multiplayer, use a jetpack to fly while holding multiple jetpacks in your inventory.

**Expected behavior**
Flight speed should be the same regardless of the number of jetpacks you are holding.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.72
 - Cucumber: 8.0.6
 - Iron Jetpacks: 8.0.4
 - Singleplayer or Multiplayer: Both

**Comment by TheBedrockMaster** [comment]
I'm having the same problem, I was changing the jetpack configs for ATM10 when I noticed.
