### ISSUE TITLE
Empty Tags for Vanilla Ores with JEI on Crafting JetPacks

### ISSUE THREAD

**Issue by MerllynGrimor** [BlakeBr0/IronJetpacks#106]
**Describe the bug**
When I'm checking the Crafts of the JetPacks (on JEI) every Ores, even the Vanilla one (beside Copper and Wood) appears as "Empty-Tags". I tryed to craft them, ignoring the JEI informations, but it does'nt work too.

**To Reproduce**
I don't really know how to reproduce it, i'm just playing on NeoForge 1.21.1 - 21.1.72 with IronJetPacks 8.0.4, cucumber 8.0.6 and JEI 19.21.0.247

**Expected behavior**
It should normally work, and be possible to craft them, because they are basic vanilla Ores.

**Screenshots / Scripts / Logs**
I attached 2 ScreenShots of the "Empty-Tags" and the non-existent result of the craft.

![IronJetPacks-Screen 1](https://github.com/user-attachments/assets/109d0a72-067b-46a5-8dc9-3079960645d3)

![IronJetPacks-Screen 2](https://github.com/user-attachments/assets/513faac2-ba23-425b-8b4a-f33531448af9)

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: (NeoForge) 21.1.72
 - Cucumber: 8.0.6
 - Iron Jetpacks: 8.0.4
 - Singleplayer or Multiplayer: SinglePlayer (For the moment)

**Comment by BlakeBr0** [comment]
If you delete (or rename) the jetpacks folder in `config/ironjetpacks/jetpacks` it should use the new tags. I'm guessing these configs were copied from an older version?

**Comment by MerllynGrimor** [comment]
I deleted the Folder, and yes, it work. I think something went wrong, and keeped the old Data or didnt upgraded, from an old version Neo/Forge 1.20.1.

**Comment by MerllynGrimor** [comment]
@BlakeBr0 Sorry, I forgetted to Thank you for the help. Love the Mod by the way!
