### ISSUE TITLE
Cannot craft stone jetpack components with vanilla stone

### ISSUE THREAD

**Issue by Nevrai** [BlakeBr0/IronJetpacks#107]
![image](https://github.com/user-attachments/assets/395bc03d-560a-4dfd-b71f-f469952c4036)
![image](https://github.com/user-attachments/assets/04996852-f216-44c2-99f5-e26f1e77ffdd)

The recipes for the stone jetpack components use the tag `c:stone`, when it _should_ be `c:stones` (some Regions Unexplored stone blocks still work because they, too, accidentally use `c:stone` [[RU: #196](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/196)]).

### Versions
* **Modpack**: [All the Mods 10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10) 1.15
* **Minecraft**: 1.21.1
* **NeoForge**: 21.1.73
* **Iron Jetpacks**: 8.0.5

**Comment by BlakeBr0** [comment]
The default ingredient for the stone jetpack is set to `c:stones`. Maybe this was changed in the modpack?

**Comment by Nevrai** [comment]
It appears to have been a bug in the modpack. It has been fixed as of All the Mods 10 version 1.16.
