### ISSUE TITLE
Baubles integration

### ISSUE THREAD

**Issue by migmolrod** [BlakeBr0/IronJetpacks#12]
Is there any chance to get [Baubles](https://github.com/Azanor/Baubles) integration with this mod? Maybe with a very expensive recipe (nether stars?) to convert the regular jetpack into a bauble jetpack, since having a jetpack + your own armor is really powerful, specially in mod packs with already somewhat overpowered armor pieces.

For example, I'm currently playing a modpack with this Iron Jetpacks mod and the Construct Armory mod (a Tinker's Construct add-on), which adds lots of armor pieces with tons of customization options.
And right now it's a pain to change between the chestplate and the jetpack. Plus the modpack difficulty is so high that you can't afford to not use your chestplate without getting oneshotted by some strong enemies (it's the World of Dragons modpack)

**Comment by BlakeBr0** [comment]
The only balancing factor of jetpacks is that they take up the chestplate slot. Your example reinforces that. It also doesn't really make sense since a jetpack is not really a bauble.

In other words I won't be adding this.
