### ISSUE TITLE
[1.14.4] Client crashed on death

### ISSUE THREAD

**Issue by Elrol** [BlakeBr0/IronJetpacks#13]
I have a log from when it happened, but I had discovered a bug with another mod, then turned around, was killed, and saw a fatal server error before my client crashed to desktop. The log is [here](https://pastebin.com/d5atcV3g)

**Comment by kreezxil** [comment]
you should include that log

**Comment by BlakeBr0** [comment]
I still have no idea what could possibly be causing this crash. I also haven't seen a crash log for this issue  where random patches isn't installed.

**Comment by BlakeBr0** [comment]
If I had to guess what was going on here: 

It looks like the client connection is destroyed but the client tick event is still being called, and trying to send the packet. I'm going to try to put in a sanity check for this and see if this stops happening.

**Comment by kreezxil** [comment]
so is this fixed or are you saying to get rid of random patches?

**Comment by kreezxil** [comment]
ok i see what you did there.
