### ISSUE TITLE
[1.15.2] Iron Jetpacks causes Datapacks not to reload.

### ISSUE THREAD

**Issue by Boomflex** [BlakeBr0/IronJetpacks#16]
Version: IronJetpacks-1.15.2-3.0.0

https://pastebin.com/9KqMxF4M

**Comment by BlakeBr0** [comment]
Are you able to reproduce this? Not entirely sure what would cause this to happen. That error says that the strap item is null or the registry object wasn't updated with the item, which should never happen.

**Comment by Boomflex** [comment]
I have just checked by the latest.log and the debug.log and it doesn't/hasn't reappeared recently.

I am now working off of a different Forge, so maybe the reason?

I would say it is a bug but a non reproducible one.

**Comment by BlakeBr0** [comment]
I'm going to assume this is fine. I've been getting a ton of issue reports about registry objects being null, when there should be no logical way that they are. It has to be some weird forge issue..
