### ISSUE TITLE
The Jetpacks stopped working for no reason

### ISSUE THREAD

**Issue by FaketyFa** [BlakeBr0/IronJetpacks#18]
Am playing AstroBlocks, the jetpacks stopped working, and can't fix it. Tried changing keybinds but still doesnt work

**Comment by BlakeBr0** [comment]
This doesn't really tell me anything. Is the engine enabled? Does it have enough power?

**Comment by BlakeBr0** [comment]
I'm going to close this as I would assume you figured out your issue or don't care anymore at this point.
