### ISSUE TITLE
Request: Proper Throttle Control

### ISSUE THREAD

**Issue by cyberdragon442** [BlakeBr0/IronJetpacks#19]
Several people have suggested this in your comments as well. But a proper throttle of some sort would definately help, especially with higher tiers, for those times when you would not want to go ludicrously fast (I know sneak flying was recently added but that's not proper speed control).

I suggest using "notches" or "steps", like an old ship EOT, with more notches per tier. Low tiers would have half and full up to emerald having slow (walking speed), 1/3, 1/2, and full (possibly adding 2/3 in between).

**Comment by dathide** [comment]
I request this as well. For now, I am editing the config files. I love the hover function on the emerald jetpack, but I can't precisely move around to build or mine in that mode because of how incredibly fast I move both horizontally and vertically.

**Comment by DeathOfTime** [comment]
I was thinking it might be nice if the higher tier packs had something called retro thrusters or similar. that could be toggled like hover mode and consumed more ef/t. that would in practice be similar to creative flight in speeds when moving. though stuff like hovering would still be in effect. so they would still hover normally
