### ISSUE TITLE
Support: Fabric Port

### ISSUE THREAD

**Issue by shedaniel** [BlakeBr0/IronJetpacks#21]
I have a fabric port of this working, do you wish to maintain that version yourself in CF by either creating a new CF project or uploading the fabric version to the same project (I don't recommend that)?

If you don't want to maintain such versions, I would be creating a fresh new CF project to maintain the fabric port.

I wish to hear your opinions on this.

**Comment by BlakeBr0** [comment]
I have no plans to ever support fabric so you can just make your own project for it.
