### ISSUE TITLE
JSON Config Changes Not Applying

### ISSUE THREAD

**Issue by Mochnant** [BlakeBr0/IronJetpacks#22]
Minecraft 1.15.2
Forge: 31.1.79
IronJetpacks 3.0.1

Editing the existing json files in /config/ironjetpacks/jetpacks/ to modify speeds, costs, etc do not seem to be applied in game after server restart.  No additional jetpacks were added.

There are no log messages for IronJetpacks that shows any issues.

Is this a known issue, and/or can I provide any diagnostic information to help find the issue?

**Comment by BlakeBr0** [comment]
You mention a server restart. Do the clients have the same config files? They need to be the same on both the server and the client.

**Comment by Mochnant** [comment]
Interesting, I’m sure that is what it is then, thank you.

Would it be possible to have these be server side so that admins could tweak numbers without updating their mod packs?

**Comment by Mochnant** [comment]
A further thought... if a client intentionally changed their local configs, it seems like their settings would be used on the server?  That seems to be a potential angle for abuse.

**Comment by BlakeBr0** [comment]
Can't be server side only because the configs are used to generate the items. Server side should always take priority for anything that matters.

**Comment by Mochnant** [comment]
I have flown with client side speed while the server config was much lower, so not sure what’s going on there.  That is to say, it does not appear as if server configs are taking precedent.
