### ISSUE TITLE
Request: Add various misc features.

### ISSUE THREAD

**Issue by brianSites** [BlakeBr0/IronJetpacks#23]
I feel the jetpacks are much more like magic rather than science powered technology. For example, the jetpack starts up instantly when you press the configured key. To combat this, I feel the jetpack should take a few seconds to fully startup. You have to hold the launch key (by default, v) for about 3 seconds and it would start as normal. I also propose you add boots that can prevent or decrease fall damage. This would help if you are on a long flight and realize your jetpack has just ran out of energy. It would also help if you are in a rush and don't have time to carefully make sure you don't take damage.

**Comment by BlakeBr0** [comment]
RF/FE is magic, so it feeling that way makes sense. I don't really feel like making the jetpacks take time to start would make them more fun to use. And as far as adding long fall boots, that's out of the scope of the mod. The idea is to just be a simple and highly configurable jetpack mod.
