### ISSUE TITLE
[1.15.2] Recipe complications with CraftTweaker

### ISSUE THREAD

**Issue by TheUntamed** [BlakeBr0/IronJetpacks#24]
If I remove the tag from an item e.g. an electrum ingot that ingot can still be used to craft the electrum jetpack and components.
This only happens for recipes of this mod. All other recipes using the item tag cannot longer use that item (because it doesn't have the tag anymore).

forge-31.2.29
Iron Jetpacks - 3.0.3

**Comment by BlakeBr0** [comment]
I'll look into this but you may end up just having to remove the generated recipes and re-add them manually.
