### ISSUE TITLE
Client Jetpack Configs used on Server

### ISSUE THREAD

**Issue by hotdog95** [BlakeBr0/IronJetpacks#25]
**Describe the bug**
The client jetpack configs will be used when joining a server, for example the speed and energy values. Bug is evident with decreased values on the client for horizontal speed.

**To Reproduce**
1. Create a server with default jetpack configs
2. tweak client jetpack speed (haven't tested with increased values)
3. Client configs will be used instead of server configs

**Expected behavior**
The client to use the server jetpack configs

**Versions:**
 - Minecraft: 1.15.2
 - Forge: 31.2.31
 - Cucumber: 3.0.9
 - Iron Jetpacks: 3.0.3

**Comment by BlakeBr0** [comment]
This should no longer be an issue in version 5.0.0 or later now that jetpacks are synced from the server to the client.
