### ISSUE TITLE
Can't add spaces to jetpack names

### ISSUE THREAD

**Issue by N1ch0l2s** [BlakeBr0/IronJetpacks#28]
Putting spaces in a jetpack's name just causes there to be a underscore between each word in the name. Capitalizing doesn't change it or anything. Would adding some sort of "fake space" character fix this? Or is there some work-around that I'm unaware of?
![EndSteelNamingIssue](https://user-images.githubusercontent.com/32824550/95551455-ad8c7900-09bf-11eb-9107-30ee5027cc41.PNG)

**Comment by BlakeBr0** [comment]
Quoting the docs:

Name*
The name of the jetpack. This name must be all lower case and have underscores for spaces. This will be used for registry names as well as localized names. The name will be formatted automatically for localized names.

https://mods.blakebr0.com/docs/ironjetpacks/jetpack-json

**Comment by N1ch0l2s** [comment]
![NotFullyCapitalizedNorSpaced](https://user-images.githubusercontent.com/32824550/96390709-bec94880-116a-11eb-878d-f041f98ec60e.PNG)
Even if I have it all lower case and have underscores for spaces, it doesn't format the names properly. I aim for "End Steel Jetpack," not "End_steel Jetpack." I'm not sure if it's some sort of encoding issue or I'm not doing it properly (last I checked _ is the underscore), but formatting the name "properly" doesn't give me the desired result.

**Comment by N1ch0l2s** [comment]
This is for the 1.12.2 version.

**Comment by BlakeBr0** [comment]
I stopped supporting the 1.12 version a long time ago. This will be fixed in the latest 1.16 version though
