### ISSUE TITLE
Can't create a perfect hover mode without making shift/space do nothing

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BlakeBr0/IronJetpacks#3]
I want to create a jetpack with a perfect hover mode for my pack. I set the `speed_hover_descend` to 0 which accomplishes this. Unfortunately it also means that pressing space or shift to ascend or descend do exactly nothing.

I'd like this setting to be broken into two different settings. `speed_hover_descend_manual` would control how much you can ascend or descend using the space/shift keys. `speed_hover_gradual_fall` would control how quickly you fall gradually just by having hover mode active.

**Comment by BlakeBr0** [comment]
speed_hover_descend changes how fast you go down while in hover mode and using shift (or space i guess), speed_hover changes the speed the jetpack descends normally while hovering. This is noted [here](https://github.com/BlakeBr0/IronJetpacks/wiki/JSON-Values).

**Comment by TheDeviantCrafter** [comment]
This worked flawlessly. Closed.
