### ISSUE TITLE
Request: CurioAPI support

### ISSUE THREAD

**Issue by seanimusprime** [BlakeBr0/IronJetpacks#31]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'd like CurioAPI support to be added so the jetpacks can be added to the back slot.

**Describe alternatives you've considered**
Using it normally in the chest slot.

**Comment by BlakeBr0** [comment]
The problem with this is it negates one of the only tradeoffs of wearing a jetpack. I consider the defensive drawback of wearing a jetpack in the chestplate slot to be an important part of the "balance" of what is a pretty powerful mod.
