### ISSUE TITLE
Iron Jetpacks hover mode crashes server instantly!

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/IronJetpacks#37]
**Describe the bug**
When i try to turn on/off hover mode on my jetpack it crashes server

**To Reproduce**
1.Click G to switch hover mode

**Expected behavior**
Just turn on hover mode

**Screenshots / Scripts / Logs**
https://pastebin.com/te673HUc

**Versions (please complete the following information):**
 - Minecraft: 1.16.5 TNP limitless 3 modpack
 - Forge: idk.
 - Cucumber: idk.
 - Iron Jetpacks: idk. (probably latest)

**Comment by Nodac80** [comment]
Issue seems to be with all jetpack controls. Had crashes with hover toggle, engine toggle, throttle up, and throttle down.

**Comment by BlakeBr0** [comment]
That crash is caused by whatever 'curiousjetpacks' is.
