### ISSUE TITLE
Strange case of briefly vanishing equipment, occasionally causing crashes

### ISSUE THREAD

**Issue by have-a-boy** [BlakeBr0/IronJetpacks#38]
**Describe the bug**
First things first, I'm playing on the [TNP Limitless 3 pack](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3).

Occasionally, seemingly at random, a piece of equipment will vanish from the players equipment slot for a very brief moment, then reappear. This is usually visible in a brief flicker of the armor bar, but causes crashes with equipment other mods, specifically Mekanism, since it doesn't expect a hydrogen powered jetpack to vanish while it's in use and actively consuming fuel. I [reported this](https://github.com/mekanism/Mekanism/issues/6815) to the Mekanism GitHub, but the Author told me that it was unlikely for Mekanism to cause this issue and after taking a look at the relevant code, I agree. Even though he has taken steps in future versions to hopefully prevent this kind of manipulation from causing a crash, I feel it's still worth looking into solving the root cause. Chestplates enchanted with Vigor will also experience this issue, causing a short damage animation before refilling the now missing health.

So I started disabling mods one by one until the issue disappeared, following some [deductive reasoning](https://github.com/The-Nexus-Project/Limitless-3/issues/64) after looking at other similar crash reports. IronJetpacks was one of the mods I isolated as potential sources and disabling it (and only it) fixed the crashes for me as well as the flickering armor bar. I've played for weeks now, constantly using the Mekanism jetpack and it hasn't happened since, whereas previously it would happen after maybe 10 minutes of gameplay, sometimes less.

This could still be down to a bad mod interaction, but I'm confident enough to file this bug report that IronJetpacks may be involved. Maybe you have an idea of what could be causing this, thanks in advance.

**To Reproduce**
1. Equip Mekanism hydrogen jetpack
2. Use the jetpack a lot
3. Hope for a crash (or watch the armor bar like a hawk)

**Versions (please complete the following information):**
 - Minecraft: 1.16.3 - 1.16.5
 - Forge: 36.0.1
 - Cucumber: 4.1.5
 - Iron Jetpacks: 4.2.0 (probably earlier versions as well)
 - [TNP Limitless 3](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3): 1.8.2 - 1.9.2

**Comment by BlakeBr0** [comment]
I'm going to close this as it doesn't seem anyone else has had this issue. If this is still an issue you can reply here.
