### ISSUE TITLE
Client uses server config on a non-server world

### ISSUE THREAD

**Issue by Blueblob860** [BlakeBr0/IronJetpacks#39]
When I load my Minecraft world on the Sky Bees modpack, the game crashes do to the mod using a server config file, even though I'm using a client. It says " Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ironjetpacks-server.toml of type SERVER for modid ironjetpacks"

Download Sky Bees version 3.0.3b
Update the Ex Nihilo: Sequentia - Mekanism Addon
Load the game, and wait about 2 minutes
Create a new world
After 1 minute the crash should appear in the Minecraft game log,

Screenshot:
![image](https://user-images.githubusercontent.com/50087969/107988922-0936c680-6f9f-11eb-860c-3552e9fcf402.png)

 - Minecraft: 1.16.4
 - Forge: 35.1.37
 - Cucumber: 4.1.6
 - Iron Jetpacks: 4.2.0

**Comment by BlakeBr0** [comment]
You're sure it's an issue with my mod? I would assume if part of the steps to reproduce the issue is to update a different mod, could it not be that one instead?

Also is there a full crash log? If the game crashes there should be a whole stack trace.

**Comment by Blueblob860** [comment]
I'm not sure if it's a mod conflict or just a problem with the mod. I also didn't get a crash report because the Minecraft wasn't responding at all.

**Comment by BlakeBr0** [comment]
Though I doubt this was an issue on my end, the next release removes the use of a server config. If there was an issue it should theoretically not happen anymore (with the next release).
