### ISSUE TITLE
jetpack sound extremely low

### ISSUE THREAD

**Issue by FelixDleon** [BlakeBr0/IronJetpacks#40]
the sound of the jetpack is not hearable at all , all my volume option are raised to 100 , I also use the jetpack from mekanism and it does have sound, may this be a incompatibility issue?

**Comment by BlakeBr0** [comment]
Are the jetpack sounds enabled in the client config?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue you can reply here.
