### ISSUE TITLE
Cant craft diamond or platinum

### ISSUE THREAD

**Issue by ckapa350** [BlakeBr0/IronJetpacks#41]
**Describe the bug**
Cannot craft components of diamond and platinum, when you attempt to craft batteries, it does not work, thus cant upgrade to be able to craft Emerald(which i was able to craft components for.

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge:36.1.2
 - Cucumber:
 - Iron Jetpacks:1.16.4-4.2.0

**Comment by BlakeBr0** [comment]
This is likely an issue with your specific modpack.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue you can reply here.
