### ISSUE TITLE
throttle not working

### ISSUE THREAD

**Issue by Trinium12** [BlakeBr0/IronJetpacks#45]
**Describe the bug**
Cant decrease throttle we can decrease the throttle when not flying but as soon as we fly it does back to 100% throttle

**To Reproduce**
just try to decrease throttle

**Expected behavior**
throttle decreases

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge:36.2.2
 - Cucumber:Cucumber-1.16.4-4.1.10
 - Iron Jetpacks:IronJetpacks-1.16.5-4.2.1

**Comment by CuboidDroid** [comment]
Hi. Any update on this one? Experiencing the same issue. Can set the throttle while on the ground, but on take-off it resets to 100% every time, and while in flight, can only drop to 80% and no lower (same versions as above, but on Forge 36.2.8)

**Comment by Trinium12** [comment]
> 
> 
> Hi. Any update on this one? Experiencing the same issue. Can set the throttle while on the ground, but on take-off it resets to 100% every time, and while in flight, can only drop to 80% and no lower (same versions as above, but on Forge 36.2.8)

never figured out why it was doing so i just lived with it lmao

**Comment by BlakeBr0** [comment]
This looks like an issue with Curious Jetpacks, see https://github.com/Tfarcenim/CuriousJetpacks/issues/15
