### ISSUE TITLE
Jetpack Sound and Particles are Visible in Spectator Mode

### ISSUE THREAD

**Issue by MojangPlsFix** [BlakeBr0/IronJetpacks#48]
**Describe the bug**
You can see the particles and hear the jetpack sound if the player is in spectator.

**To Reproduce**

1. Equip Jetpack
2. Go into spectator
3. Press Space

**Expected behavior**
The jetpack should be hidden and not make any particles or sound.

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/6189957/146051609-8377ea18-0d30-4343-be20-fd0a139f6785.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.20
 - Cucumber: 4.1.12
 - Iron Jetpacks: 4.2.3

**Comment by BlakeBr0** [comment]
This is fixed in the latest version for 1.18. I'm going to leave this open for now just incase I end up releasing another version for 1.16.

**Comment by BlakeBr0** [comment]
I'm going to close this as I don't plan on releasing another 1.16 version.
