### ISSUE TITLE
Log spam 1.18.1

### ISSUE THREAD

**Issue by nanonestor** [BlakeBr0/IronJetpacks#54]
**Describe the bug**
constant log spam (dedicated server)

latest.log
[https://paste.gg/p/anonymous/54b042378f0948aa96e63c43ae69981d](https://paste.gg/p/anonymous/54b042378f0948aa96e63c43ae69981d)
snip of spam
[https://paste.gg/p/anonymous/a0a5fc73105746989942db61a0f2bc50](https://paste.gg/p/anonymous/a0a5fc73105746989942db61a0f2bc50)

**To Reproduce**
Load the versions below (dedicated server environment) and have players join.

**Expected behavior**
No log spam from some deprecated feature(s)

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.1.2
 - Cucumber: 5.0.3
 - Iron Jetpacks: 5.0.2

**Comment by BlakeBr0** [comment]
Is this issue still happening on the latest version?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
