### ISSUE TITLE
Maybe a durability issue

### ISSUE THREAD

**Issue by CrazyWolf13** [BlakeBr0/IronJetpacks#56]
**Describe the bug**
My jetpacks dissapear sometimes after get hit by entitys i think its caused cause of durability

**To Reproduce**
let a mob damage your jetpack

**Expected behavior**
1. give if infinite durability
2. make it possible to change the value
3.make it possible to /give a jetpacks they i could change with attribute modifiers

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge:39.1.0
 - Cucumber:1.18.1-5.0.3
 - Iron Jetpacks:1.18.1-5.0.2

**Comment by BlakeBr0** [comment]
I am unable to reproduce this. Perhaps there is another mod involved that is deleting your jetpack or improperly handling damage?

**Comment by CrazyWolf13** [comment]
> I am unable to reproduce this. Perhaps there is another mod involved that is deleting your jetpack or improperly handling damage?

Not really....
I just flew around in a cave with mobs and out of nowhere it dissapeared, this happend twice now.

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?
