### ISSUE TITLE
Jetpack refills to level on equipping in curio slot

### ISSUE THREAD

**Issue by Sonic1305** [BlakeBr0/IronJetpacks#57]
**Describe the bug**
The jetpack refills to the fuel level it was when putting it in the curio slot if I toggle hover or engine mode. This can be abused to have unlimited fuel.

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 1.18.2-40.1.20
 - Cucumber: 1.18.2-5.1.0
 - Iron Jetpacks: 1.18.2-5.1.1

**Comment by BlakeBr0** [comment]
I was able to reproduce this on a server. Seems to work fin in singleplayer.
