### ISSUE TITLE
[Suggestion] Ability to combine with armor

### ISSUE THREAD

**Issue by SynexWolf** [BlakeBr0/IronJetpacks#6]
I would like to see that you will be able to combine the jetpack with armor so you can fly while still wearing armor, I understand that you can set the armor points for jetpacks, but it would great if you could combine it.

**Comment by BlakeBr0** [comment]
The only balancing factor of jetpacks is that they take up the chestplate slot. This would remove that entirely and make them have no downsides, which I'm not a fan of.
