### ISSUE TITLE
Add new optional json key `localization_name` to cover default generated name

### ISSUE THREAD

**Issue by CubeSugarCheese** [BlakeBr0/IronJetpacks#61]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Noticed that all jetpack have same key, so translator can't provide translate across Resource Pack. Also, key `name` must be all lower case and have underscores for spaces. So translator can't edit it.

**Describe the solution you'd like**
Add new optional json key `localization_name` to cover default generated name

**Additional context**
I am a Chinese translator. I try to edit modpack's config file to provide translate, but it give me `undefined` as jetpack's name.

**Comment by BlakeBr0** [comment]
I think for this I'm going to make it so the translation key is automatically generated based on the  jetpack name. Ex. 'jetpack.<jetpack_name>.name`  or something similar, and fall back to the current behavior if there isn't any lang entries defined for it.

If that doesn't work I'll add an optional localization_key field that lets you specify that translation key manually.

**Comment by BlakeBr0** [comment]
You'll be able to translate the jetpack names via a resource pack in the next release.

https://blakesmods.com/docs/ironjetpacks/jetpack-json#name
