### ISSUE TITLE
Character slides down wall when near edge

### ISSUE THREAD

**Issue by Geccpls** [BlakeBr0/IronJetpacks#64]
**Describe the bug**
While wearing a jetpack in hover mode, flying too close to the upper edge of a block will make start to move downwards in an awkward stutter, making a sound similar to a footstep but much faster and more annoying. 

**To Reproduce**
Stand on a block. Enable hover. Move off the block. Slowly approach the block again, so that you don't fully step onto the block- Imagine touching it with the tip of your toe. It may take a couple tries, but then you'll start stuttering downwards. If you do this while facing a corner where 2 blocks meet, it seems you'll stutter all the way down. 

Moving away from the block while this is happening cancels the downward stuttering.

**Expected behavior**
That you remain at the same height regardless of being next to blocks.

**Screenshots / Scripts / Logs**
https://imgur.com/a/aCRxYBb

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.57
 - Cucumber: 5.1.2
 - Iron Jetpacks: 5.1.2
 - Modpack: custom, based on Enigmatica 8

**Comment by Geccpls** [comment]
Clarifying, this can happen even when not on an edge- I think it might have to do with being very close to a block without touching it? Either way, it can happen against sheer cliffs as well.

**Comment by Geccpls** [comment]
Further addendum, going straight up also does not cancel the stutter, until you pass the blocks that are causing it.

**Comment by BlakeBr0** [comment]
I tested locally on both a server and single player world and was not able to reproduce this. Perhaps there's another factor involved in what you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
