### ISSUE TITLE
Crash: mouseClicked event handler

### ISSUE THREAD

**Issue by oguh43** [BlakeBr0/IronJetpacks#69]
**Describe the bug**
1) Add mod
2) Single player
3) Create new world
4) Crash

**To Reproduce**
1) Add mod
2) Single player
3) Create new world
4) Crash

**Expected behavior**
Not crashing

**Screenshots / Scripts / Logs**
[crash-2023-02-19_20.47.51-client.txt](https://github.com/BlakeBr0/IronJetpacks/files/10777781/crash-2023-02-19_20.47.51-client.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 1.19.2-forge-43.2.4
 - Cucumber: 1.19.2-6.0.6
 - Iron Jetpacks: 1.19.2-6.0.1

**Comment by BlakeBr0** [comment]
Does this happen every time or did it only happen once?

**Comment by oguh43** [comment]
> Does this happen every time or did it only happen once?

Every time. Could not start the server with this mod present :(

**Comment by oguh43** [comment]
Wait, could this be a compatibility issue with 1.19.2?

**Comment by BlakeBr0** [comment]
Do you have the full log?

**Comment by oguh43** [comment]
[2023-02-20-1.log.gz](https://github.com/BlakeBr0/IronJetpacks/files/10869969/2023-02-20-1.log.gz)
[2023-02-20-2.log.gz](https://github.com/BlakeBr0/IronJetpacks/files/10869970/2023-02-20-2.log.gz)
[2023-02-20-3.log.gz](https://github.com/BlakeBr0/IronJetpacks/files/10869971/2023-02-20-3.log.gz)
[2023-02-20-4.log.gz](https://github.com/BlakeBr0/IronJetpacks/files/10869972/2023-02-20-4.log.gz)

**Comment by oguh43** [comment]
Those are the oldest ones i have. Also this bug happend in previous versions of this and cucumber mod.

**Comment by BlakeBr0** [comment]
I'm not entirely sure what would cause this. I feel there must be a weird mod interaction going on with your modpack.

**Comment by ForgottenUmbrella** [comment]
In my case, Create Slice & Dice appears to be related to the "weird mod interaction" that causes the crash whenever I click "Create New World" in the world selection screen (or "Singleplayer" in the main menu if no worlds had been created yet).

Here's my crash report, with the minimal number of mods necessary to reproduce:
[crash-2023-04-08_19.12.39-client.txt](https://github.com/BlakeBr0/IronJetpacks/files/11182878/crash-2023-04-08_19.12.39-client.txt)

**Comment by DrollestDuck88** [comment]
> > Does this happen every time or did it only happen once?
> 
> Every time. Could not start the server with this mod present :(

it's my case too 
but i have a bit more mods so it's harder to know wich one is making me crash

**Comment by BlakeBr0** [comment]
So I finally got this issue to happen for me and it does seem to be if Create Slice & Dice is also installed. It broke twice in a row with it installed then worked fine when I disabled it. 

I just recently made changes to Cucumber in 1.20 which would fix this error. This should be fixed in the next release for 1.20, and I'll look into backporting the fixes to the 1.19 versions as well.

**Comment by BlakeBr0** [comment]
This should be fixed with Cucumber 6.0.8 and Iron Jetpacks 6.0.5, as well as with the latest releases for 1.19.3/1.19.4,
