### ISSUE TITLE
Elytra compatibility

### ISSUE THREAD

**Issue by UrBoiTom** [BlakeBr0/IronJetpacks#71]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Elytra does not work very well with jetpacks.

**Describe the solution you'd like**
Jetpacks should propel you in the direction you are facing when elytra is also equipped, like with mekanism  jetpacks.

**Comment by BlakeBr0** [comment]
Unless I'm missing something I'm not sure how you would wear both an elytra and a mekanism jetpack.

**Comment by BlakeBr0** [comment]
I've made some changes to how the Jetpacks interact with Elytra so I'm going to close this. I don't think I'm going to make it specifically increase movement speed while falling with an Elytra however.
