### ISSUE TITLE
Jetpack upgrades continue to consume FE even after fully charged and disabled

### ISSUE THREAD

**Issue by AgentNero** [BlakeBr0/IronJetpacks#72]
**Bug Description:**

Jetpack upgrades continue to consume FE while in inventory, even after fully charged.

**To Reproduce:**
Manually crafting any jetpack upgrade, ranging from stone to Emerald(including variants), will continue to deplete energy from any of battery(i.e; Flux Capacitor) even after fully charged in inventory. Spawned in jetpacks are unaffected.

Note: this can be random at times since sometimes upgrades dont cause this behavior. But they do happen to most jetpacks 

**Expected behavior**
After fully charging the jetpack should stop consuming FE and continue to work as intended

**Versions:**
 - Minecraft: 1.19.2
 - Forge: 43.2.4
 - Cucumber: 6.0.6
 - Iron Jetpacks: 6.0.3

**Comment by BlakeBr0** [comment]
I think there's some weirdness going on with the flux capacitors. It would delete energy like crazy while charging the mekanism atomic disassembler and it would just delete energy. It would also start deleing energy after doing a recipe transfer with JEI with no chargeable items in my inventory. Have you had similar experiences to this?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
