### ISSUE TITLE
Enhanced hover mode operation

### ISSUE THREAD

**Issue by bigtruckin78** [BlakeBr0/IronJetpacks#73]
Have hover mode activated by double tapping the space bar to fly. Then once you land, hover mode is automatically disabled. It'd greatly increase usability by not having to switch hover on and off all the time and it would also be more like vanilla creative flight.

**Comment by BlakeBr0** [comment]
Thanks for the suggestion! Personally I feel like having to manually toggle and manage the jetpack controls is one of the core trade-offs of using a jetpack. I don't think jetpacks should work the same way as creative flight.
