### ISSUE TITLE
can not fly wile using controllable mod

### ISSUE THREAD

**Issue by x-j0nnay-x** [BlakeBr0/IronJetpacks#75]
I've been trying to use the iron jetpack mod with controllable and i just can seem to get it to work. i am using a ayaneo geek to play Minecraft on the go. its kind of like the steam deck. i cant seem to figure it out if i remove controllable mod and use a keyboard it works once controllable is installed it no longer works.

**Comment by BlakeBr0** [comment]
I've never used that mod before. Maybe you have to change the keybinds manually?

**Comment by x-j0nnay-x** [comment]
Controllable lets you play minecraft with a controller. ive changed the key binding to toggle engine and everything else in to key binding settings, they all work besides flying. but the way flight is turned on dose not seem to register if i use a keyboard it works. but with controllable using a handheld computer xbox input holding a to jump does not turn on the jet pack.

**Comment by BlakeBr0** [comment]
I just tested with an Xbox controller and it seems like pressing A will cause the player to jump, but setting a keybinding to A in the settings considers it a Left Click. I think the simplest solution is to have an unbound-by-default Ascend keybinding that when unbound will just default to jump like it currently does.

**Comment by BlakeBr0** [comment]
After testing it doesn't seem that adding a keybinding for it works. I'm not sure if there's anything I can do on my end to make it work.
