### ISSUE TITLE
Minecraft 1.16.5 weird stuff are happening (No Recipes for Jetpack Components, Can't Changee the speed)

### ISSUE THREAD

**Issue by xsmerREAL** [BlakeBr0/IronJetpacks#76]
i remember that it had recipes but then i deleted the mod cause i had this can't change speed issue and it was like 3-5 months ago and now i'm back with this mod and i have the latest version and still can't change speed but also there are no recipes for jetpack components ;/

**Comment by BlakeBr0** [comment]
Are all jetpacks missing recipes? I'm also not sure what you mean by changing speed. Are you changing them in the json files?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
