### ISSUE TITLE
[1.20.1] Datapack error with Create: Slice & Dice mod and IronJetpacks

### ISSUE THREAD

**Issue by lays24mc** [BlakeBr0/IronJetpacks#77]
**Describe the bug**

If the mod Create: Slice & Dice is included, I will no longer be able to join my world. The client directly shows a datapack error. The client does not crash!

If I set all "dynamic recipe options" in the ironjetpacks-common.toml to false, I can join the world again, but then of course the jetpacks don't go to crafted :)

**Screenshots / Scripts / Logs**

Excerpt from the latest.log: https://pastebin.com/CsGEUkeL 

![grafik](https://github.com/BlakeBr0/IronJetpacks/assets/38819519/10461bc1-94f6-4ce0-9be5-0e4ffcea5749)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 7.0.0 (and tested with 7.0.1)
 - Iron Jetpacks: 7.0.0
 - Create Slice & Dice: 3.1.1

**Comment by BlakeBr0** [comment]
Fixed in release 7.0.1,

**Comment by lays24mc** [comment]
Sorry for the late reply. Works fine now with 7.0.1. Thank you :)
