### ISSUE TITLE
Prevents World Creation on 1.18.2

### ISSUE THREAD

**Issue by SleepyZephrix** [BlakeBr0/IronJetpacks#79]
The 1.18.2 version (Unsure if others are affected currently) prevents the creation of worlds due to a "bad datapack"

**To Reproduce**
Create a world on the newest version of Iron Jetpacks

![image](https://github.com/BlakeBr0/IronJetpacks/assets/137726898/27d4b3bd-373a-4bd6-a970-0c0070bfaa88)
[Error.txt](https://github.com/BlakeBr0/IronJetpacks/files/13194084/Error.txt)

**Expected behavior**
When the world is created, it should start generating chunks and load you into the world

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.2.10
 - Cucumber: 5.1.4
 - Iron Jetpacks: 5.1.4

**Comment by BlakeBr0** [comment]
This should be fixed in version 5.1.5 of Cucumber.
