### ISSUE TITLE
Frame loss due to overlay 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [BlakeBr0/IronJetpacks#8]
## Version Information
`Minecraft: `1.12.2
`Forge: `2822
`Iron Chests: `1.1.0

## Report Information
I noticed that the overlay is draining FPS very much. Measured by the mod and was right. When I take a jet pack, the FPS grows by 100 frames.

https://i.gyazo.com/a10f56d9767583a93140421290de510a.png

**Comment by BlakeBr0** [comment]
I'm going to close this since I'm not working on 1.12 anymore. This shouldn't be an issue in the newer versions anymore.
