### ISSUE TITLE
[Bug] Iron Jetpacks <-> Entity Model Features crash

### ISSUE THREAD

**Issue by Fnige** [BlakeBr0/IronJetpacks#80]
**Describe the bug**
Rendering a jetpack in any way (third person + inventory tested), the game instantly crashes if you also have Entity Model Features installed

**To Reproduce**
1. Install the mods listed down below
2. Get yourself and wear any jetpack (only tested with diamond and creative but im pretty sure any works)
3. Go into your inventory or into third person
4. explosion.gif

**Expected behavior**
The game should be able to render the jetpack without throwing a tantrum

**Screenshots / Scripts / Logs**
https://gist.github.com/Fnige/2d8fefc243a2115fdb6f6716ca407d84

**Versions:**
 - Minecraft: 1.20.1
 - Forge: 47.2.1
 - Cucumber: 7.0.4
 - Iron Jetpacks: 7.0.2
 - Entity Texture Features: 4.6
 - Entity Model Features: 1.0.2

Other issue: https://github.com/Traben-0/Entity_Model_Features/issues/140

**Comment by BlakeBr0** [comment]
Based on the crash report it would be an issue with however they are generating resource locations for something. I don't think there's anything on my end that would be causing this.

**Comment by BlakeBr0** [comment]
I just tested with IJ 7.0.3 and EMF 1.2.3 and it didn't seem to crash. Is this still an issue you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
