### ISSUE TITLE
Iron jetpacks don't hold charge.

### ISSUE THREAD

**Issue by jridew** [BlakeBr0/IronJetpacks#81]
I have added iron jetpacks to a modpack I have created with some friends, after creating the emerald jetpack I needed to charge it like normal. Using a gas burning generator from the Mekanism mod I am unable to place the jetpack into the charging slot. After I tried to use the flux mod to wirelessly charge the jetpack. The jetpack will only charge **sometimes** after switching to creative and even then it wont hold the charge after placing onto my armor or curios slot and will say 0/0 fe.

Acquire emerald jetpack
Try charging using gas burning generator/flux wireless charging
Nothing happens and will switch to 0/0 fe after moving the jetpack around in my inventory.

I expected to have the jetpack charge and then be able to use it.

 - Minecraft: 1.20,1
 - Forge: 47.2.0
 - Iron Jetpacks: 7.0.2
 - Mekansim: 10.4.5.19
 - Flux Networks: 7.2.0.14

the modpack is used was through curseforge "LokisCatCafe" version 2.1

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
