### ISSUE TITLE
Cannot change jetpack recipes

### ISSUE THREAD

**Issue by Octelly** [BlakeBr0/IronJetpacks#82]
**Describe the bug**
KubeJS isn't able to replace IronJetpacks recipes

**To Reproduce**
Try to replace recipes with KubeJS

**Expected behavior**
Recipes should be changed

**Screenshots / Scripts / Logs**
Here's the janky script I use:
```js
function jetpacks(event) {
    event.remove({ mod: 'ironjetpacks' })
    event.remove({ id: /ironjetpacks:.*/ })
    event.remove({ mod: 'mekanism', output: /mekanism:.*jetpack.*/ })
    event.remove({ output: MEK('module_jetopack_unit') })

    function capacitor(tier) {
        event.shaped(Item.of('ironjetpacks:capacitor', `{Id:"ironjetpacks:${tier}"}`), [
            'MMM',
            'EEE',
            'MMM'
        ], {
            M: F(`#ingots/${tier}`)
        })
    }

    capacitor('iron')
    event.shaped(Item.of('ironjetpacks:jetpack', '{Id:"ironjetpacks:iron",Throttle:1.0d}'), [
        'SCS',
        'MBM',
        ' M '
    ], {
        S: 'create_dd:steel_ingot',
        C: MEK('basic_control_circuit'),
        M: MC('iron_ingot'),
        B: Item.of('ironjetpacks:cell', '{Id:"ironjetpacks:iron"}')
    })

    function tier(previous_tier, tier, control_circuit) {
        capacitor(tier)

        event.shaped(Item.of('ironjetpacks:jetpack', `{Id:"ironjetpacks:${tier}",Throttle:1.0d}`), [
            'MCM',
            'MJM',
            'MBM'
        ], {
            M: F(`#ingots/${tier}`),
            C: control_circuit,
            J: Item.of('ironjetpacks:jetpack', `{Id:"ironjetpacks:${previous_tier}",Throttle:1.0d}`),
            B: Item.of('ironjetpacks:capacitor', `{Id:"ironjetpacks:${tier}"}`)
        })
    }

    tier('iron', 'steel', MEK('advanced_control_circuit'))
    tier('steel', 'diamond', MEK('elite_control_circuit'))
    tier('diamond', 'emerald', MEK('ultimate_control_circuit'))
}
```

**Versions (please complete the following information):**
 - Minecraft: `1.18.2`
 - Forge: `40.2.14`
 - Cucumber: `5.1.5`
 - Iron Jetpacks: `5.1.4`

**Comment by BlakeBr0** [comment]
If you set the `craftingMaterial` value in the jetpack JSON to `"null"` it won't generate the default recipes for that jetpack. You'll also have to re-add the recipes for all the crafting components for that jetpack.

**Comment by Octelly** [comment]
@BlakeBr0 Oh! I had no idea. You should totally mention that in the docs (unless I'm just blind and didn't notice).

Sorry for bothering you in that case, haha. :heart: 

(I'll look into it later today, it is currently morning for me)

**Comment by Octelly** [comment]
![image](https://github.com/BlakeBr0/IronJetpacks/assets/29976879/ad77d01b-6c5c-4bde-a7dc-f86fa3859c0b)
Yeah, the documentation makes it sound like you have to include a material.

Although _(and I just noticed this)_ you do use `"null"` by default in the creative jetpack's JSON.

Anyway, thank you for your help, everything seems to work perfectly now!
