### ISSUE TITLE
Recipes for JetPacks not showing in JEI/REI when in Survival mode

### ISSUE THREAD

**Issue by M3wP** [BlakeBr0/IronJetpacks#83]
**Describe the bug**
The JetPack recipes aren't being shown in the JEI or REI when in Survival mode.  After entering Creative mode, the recipes are shown.  You can switch to Creative mode and back again to see the recipes.

**To Reproduce**
Use a ModPack with JEI/REI?  Start the game in Survival mode.  Try to view the recipes.

**Expected behavior**
The recipes should be shown in Survival mode the same as for Creative mode.

**Screenshots / Scripts / Logs**

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Cucumber: 7.0.6
 - Iron Jetpacks: 7.0.2
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
I'm not 100% sure what could be going on here. I think there's a feature in Minecraft that makes it so you have to discover recipes to be able to view them in the recipe book. Maybe that's what's happening here?

**Comment by M3wP** [comment]
I think its probably a problem with REI.  There were some other issues with it not displaying recipes properly, also.  Have since changed to JEI + EMI instead and having no problems.


________________________________
