### ISSUE TITLE
Charging Bug

### ISSUE THREAD

**Issue by magicicecube** [BlakeBr0/IronJetpacks#85]
**Describe the bug**
bug makes it so the jet pack wont be able to slot in an FE charging mod, also loses battery charging from Powah. (after further testing the only way for me to charge the jetpacks is to put them in the output slot of the sophisticated backpacks battery upgrade slot.).
Have not figured out a way to charge with battery packs/FE powah/Mekanism/AE2

**To Reproduce**
all was fine, until i crafted and slotted(curio mod) a Basic Battery from Powah, then i noticed the jetpack not taking power from there.(the exact circumstance is unknown, worked fine with a starter battery. note the battery was charged before slotting.

**Expected behavior**
expected normal charging functionality

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/IronJetpacks/assets/40704412/a4be60f5-478b-4921-902b-d5f522018038)
![image](https://github.com/BlakeBr0/IronJetpacks/assets/40704412/e5176ae4-8e45-44b8-8764-e36bc17145c2)
aaaaaaaaaaaaaaa

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: v0.242.1.15579
 - Cucumber:
 - Iron Jetpacks: latest ver./ATM9 ver.
 - Singleplayer or Multiplayer: single player

**Comment by tiwuno** [comment]
Also experiencing this bug with the FTB Presents Direwolf20 1.20 pack. Jetpacks won't charge in Ender IO's wired charger, Solar Flux Reborn's solar panels, etc. Ended up cheating in a creative jetpack as a temporary solution, but sure would be nice to play the mod as it was intended! ☹️

**Comment by magicicecube** [comment]
edit: i have managed to get charging working through Powah wireless charging, any other charging blocks still don't work for me (backpack excluded). side note it only started working after updating the mod-pack ATM9 to the latest version.

**Comment by BlakeBr0** [comment]
After testing a couple things in ATM 9 (0.2.51) I'm not sure how to reproduce this. I tried a basic battery as a curio and it worked, as well as putting the jetpack into the Ender IO charger and a Mekanism Energy Cube. I tried a Powah energy cell and it wouldn't take it but I think that's just how that block works. Is this still an issue you guys are experiencing?

**Comment by magicicecube** [comment]
> After testing a couple things in ATM 9 (0.2.51) I'm not sure how to reproduce this. I tried a basic battery as a curio and it worked, as well as putting the jetpack into the Ender IO charger and a Mekanism Energy Cube. I tried a Powah energy cell and it wouldn't take it but I think that's just how that block works. Is this still an issue you guys are experiencing?

the way it initially started was by upgrading a starter battery to a basic battery(after the upgrade you could slot it, but no power was extracted/routed to IronJP. my solution was backpack/wireless charging  .never ended up getting it to work with Mekanism, and i've not yet had time to try to use Ender IO. I'll get back to you once i'm home from holidays and have time to sit behind the screen. worst case i can always mega.nz the world DL. i'm not discounting user installation error/modload error yet. more news to come. kind regards

PS: powah energycell doesnt take anything but upgrades specific to powah. (it's like a buffer between power distribution/smallish scale power storage.) if that's not how it should behave then i might have an install that's scuffed beyond reprieve.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
