### ISSUE TITLE
JEI crash with Iron Jetpacks 1.19.2

### ISSUE THREAD

**Issue by Enterprise12nx01** [BlakeBr0/IronJetpacks#86]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Use this with jei and scroll through the pages until you reach this mod, crash.
removing this mod fixes it

**Expected behavior**
no crash with jei

**Screenshots / Scripts / Logs**
[Please add your logs and scripts (if applicable).](https://pastes.io/l6ev9ftkv7)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.3.7
 - Cucumber: 6.0.10
 - Iron Jetpacks: 6.0.7
 - Singleplayer or Multiplayer: Both

**Comment by BlakeBr0** [comment]
That crash comes from the `powersuits` mod.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
