### ISSUE TITLE
It is recommended to change the interaction logic to learn the Gem equipment of Project

### ISSUE THREAD

**Issue by gjmhmm8** [BlakeBr0/IronJetpacks#87]
It is recommended to change the interaction logic to learn the Gem equipment of Project

**Comment by BlakeBr0** [comment]
I'm not sure what you mean honestly

**Comment by gjmhmm8** [comment]
you can add an operational logic for jetpacks like projecte Gem equipment

**Comment by gjmhmm8** [comment]
Press and hold the jump key to fly up, release the fall, double tap to enter hover mode

**Comment by gjmhmm8** [comment]
It is best to block the disabling of flights

**Comment by BlakeBr0** [comment]
I think I'm just going to stick with the current system of having a keybind to toggle hover mode. Thanks for the suggestion!
