### ISSUE TITLE
Unable to toggle the engine on, without any key issues.

### ISSUE THREAD

**Issue by Joko-w** [BlakeBr0/IronJetpacks#97]
**Describe the bug**
Unable to toggle the jetpack engine on. There's no key conflicts, the key isn't used anywhere else. I can decrease the throttle, set the hover on and off. In the "key.txt" file, in the instance folder, there's no ironjetpacks keys. I have the bug on Curseforge and Prism launcher, haven't tried anywhere else. 

**To Reproduce**
I am playing in ATM 9.

**Expected behavior**
The jetpack engine is supposed to be on with a text over my hotbar and the icon on the left switching green with "ON"

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge:47.2.20
 - Cucumber:7.0.8
 - Iron Jetpacks:7.0.6
 - Singleplayer or Multiplayer: Both

**Comment by BlakeBr0** [comment]
I wasn't able to reproduce this issue. Are you still experiencing this?

**Comment by Joko-w** [comment]
After upgrading the modpack to the latest version, I reconfigured my keys and it happens that there was two different categories, so I had to attribute the keys twice.

**Comment by BlakeBr0** [comment]
Yeah there's `Toggle Engine` in the `Iron Jetpacks` category and `Toggle Jetpack Engine` in `key.categories.movement.jetpack`. The second one is for another mod.
